# docker run -it --rm --entrypoint htpasswd registry:2 -Bn USER | grep '\$' | sudo tee -a ./registry/auth/registry.password
# docker run --rm --entrypoint htpasswd registry:2 -Bbn testuser testpassword | sudo tee -a ./registry/auth/registry.password
# docker cp docker-registry_registry_1_*:/certs/domain.crt ./domain.crt
# sudo scp -P # rguzman@X.X.X.X:/home/rguzman/Documents/docker-compose/docker-registry/domain.crt /etc/docker/certs.d/X.X.X.X/
# docker-compose up -d --build
version: '2.4'
services:
  registry:
    build: ./registry
    image: main-registry:v2.0
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      URL: datajoint.io
      SUBDOMAINS: raphaelg
      PUBLIC_IP: 192.168.1.205
    # ports:
    # - "443:5000"
    volumes:
      # - ./registry/auth:/auth
      # - ./registry/data:/data
      - /docker-mnt/docker-registry/auth:/auth
      - /docker-mnt/docker-registry/data:/data
    networks:
      - main     
  nginx:
  build: ./nginx
    image: registry-nginx:v1.0
    environment:
      - PUID=1000
      - PGID=1000
      - EMAIL=raphael@vathes.com
      - URL=datajoint.io
      - SUBDOMAINS=raphaelg
      - TZ=Europe/London
      - ONLY_SUBDOMAINS=true
      - STAGING=true
    ports:
      - "80:80"
      - "443:443"
    # cap_add:
    #   - NET_ADMIN
    # volumes:
    #   - ./nginx-letsencrypt/app.conf:/config/nginx/site-confs/app.conf
    networks:
      - main   
    # depends_on:
    #   registry:
    #     condition: service_healthy
networks:
    main:
        ipam:
            driver: default
            config:
                - subnet: 10.28.0.0/16

